var POLICY_META = {
  title: "RAV Policy Navigator",
  scope: "United States federal policy and Georgia implementation context",
  verified: "2026-07-30",
  disclaimer: "Educational policy-planning resource; not legal advice."
};

var POLICIES = [
  {
    id: "fed-av-framework-2025",
    title: "2025 Automated Vehicle Framework",
    issuer: "U.S. Department of Transportation",
    jurisdiction: "Federal",
    domain: "Safety assurance",
    instrument: "Policy framework",
    status: "Current framework",
    year: 2025,
    binding: false,
    rural: "Direct",
    summary: "Organizes the federal approach around safety, removal of unnecessary regulatory barriers, and commercial deployment.",
    ruralAction: "Use the framework to separate federal vehicle-safety questions from state operating rules and local pilot controls.",
    url: "https://www.transportation.gov/briefing-room/trumps-transportation-secretary-sean-p-duffy-unveils-new-automated-vehicle-framework"
  },
  {
    id: "nhtsa-av-safety",
    title: "Automated Vehicle Safety Resource Hub",
    issuer: "National Highway Traffic Safety Administration",
    jurisdiction: "Federal",
    domain: "Safety assurance",
    instrument: "Agency resource",
    status: "Current guidance",
    year: 2025,
    binding: false,
    rural: "Transferable",
    summary: "Central NHTSA resource describing automated-driving safety oversight, federal activity, testing, and deployment resources.",
    ruralAction: "Anchor the pilot safety case to NHTSA terminology and distinguish driver assistance from an automated driving system.",
    url: "https://www.nhtsa.gov/vehicle-safety/automated-vehicles-safety"
  },
  {
    id: "nhtsa-sgo-2025",
    title: "Standing General Order on Crash Reporting",
    issuer: "National Highway Traffic Safety Administration",
    jurisdiction: "Federal",
    domain: "Safety assurance",
    instrument: "General order",
    status: "In force",
    year: 2025,
    binding: true,
    rural: "Direct",
    summary: "Requires identified manufacturers and operators to report qualifying crashes involving ADS or Level 2 ADAS-equipped vehicles.",
    ruralAction: "Create an incident classification, escalation, preservation, and reporting workflow before public-road operations begin.",
    url: "https://www.nhtsa.gov/laws-regulations/standing-general-order-crash-reporting"
  },
  {
    id: "nhtsa-vssa",
    title: "Voluntary Safety Self-Assessment",
    issuer: "National Highway Traffic Safety Administration",
    jurisdiction: "Federal",
    domain: "Safety assurance",
    instrument: "Voluntary guidance",
    status: "Current guidance",
    year: 2017,
    binding: false,
    rural: "Direct",
    summary: "Provides a disclosure structure for explaining how an ADS developer addresses recognized safety elements.",
    ruralAction: "Publish a route-specific safety case covering the rural operational design domain, fallback, data recording, and validation.",
    url: "https://www.nhtsa.gov/automated-driving-systems/voluntary-safety-self-assessment"
  },
  {
    id: "nhtsa-part-555",
    title: "Part 555 Automated-Vehicle Exemption Process",
    issuer: "National Highway Traffic Safety Administration",
    jurisdiction: "Federal",
    domain: "Vehicle compliance",
    instrument: "Exemption program",
    status: "Active program",
    year: 2025,
    binding: true,
    rural: "Conditional",
    summary: "Provides a process for limited production of vehicles that do not fully comply with particular FMVSS requirements when statutory findings are met.",
    ruralAction: "Determine early whether the proposed vehicle configuration needs an exemption and budget time for the federal process.",
    url: "https://www.nhtsa.gov/press-releases/streamline-exemption-process-noncompliant"
  },
  {
    id: "nhtsa-avep",
    title: "Automated Vehicle Exemption Program",
    issuer: "National Highway Traffic Safety Administration",
    jurisdiction: "Federal",
    domain: "Vehicle compliance",
    instrument: "Demonstration exemption",
    status: "Active program",
    year: 2025,
    binding: true,
    rural: "Conditional",
    summary: "Expanded NHTSA's demonstration exemption pathway to include domestically produced noncompliant automated vehicles.",
    ruralAction: "Match the intended research or demonstration use to the correct exemption pathway before procuring a novel vehicle.",
    url: "https://www.nhtsa.gov/document/automated-vehicle-exemption-program-domestic-exemptions"
  },
  {
    id: "nhtsa-occupant-protection",
    title: "Occupant Protection for Vehicles Without Driving Controls",
    issuer: "National Highway Traffic Safety Administration",
    jurisdiction: "Federal",
    domain: "Vehicle compliance",
    instrument: "Final rule",
    status: "In force",
    year: 2022,
    binding: true,
    rural: "Transferable",
    summary: "Updates occupant-protection standards for ADS-equipped vehicles that do not have traditional manual driving controls.",
    ruralAction: "Treat novel cabin layouts as a compliance and crashworthiness question, not only a service-design decision.",
    url: "https://www.nhtsa.gov/press-releases/nhtsa-finalizes-first-occupant-protection-safety-standards-vehicles-without-driving"
  },
  {
    id: "fhwa-automation",
    title: "Automated Vehicle Activities and Resources",
    issuer: "Federal Highway Administration",
    jurisdiction: "Federal",
    domain: "Infrastructure",
    instrument: "Program resource",
    status: "Active program",
    year: 2025,
    binding: false,
    rural: "Direct",
    summary: "Connects highway agencies with FHWA automation, infrastructure, cooperative-driving, research, and outreach resources.",
    ruralAction: "Use FHWA resources to frame roadway-owner responsibilities and avoid assuming the vehicle alone controls every risk.",
    url: "https://highways.dot.gov/automation"
  },
  {
    id: "fta-policy-faq",
    title: "Transit Bus Automation Policy FAQs",
    issuer: "Federal Transit Administration",
    jurisdiction: "Federal",
    domain: "Transit operations",
    instrument: "Policy guidance",
    status: "Current guidance",
    year: 2026,
    binding: false,
    rural: "Direct",
    summary: "Addresses federal and FTA policy questions that arise when transit agencies evaluate automated buses.",
    ruralAction: "Use the FAQs as a pre-procurement checklist for a rural transit or shuttle project receiving federal support.",
    url: "https://www.transit.dot.gov/research-innovation/transit-bus-automation-policy-faqs"
  },
  {
    id: "fta-bus-testing",
    title: "FTA Bus Testing Program",
    issuer: "Federal Transit Administration",
    jurisdiction: "Federal",
    domain: "Transit operations",
    instrument: "Compliance program",
    status: "In force",
    year: 2026,
    binding: true,
    rural: "Conditional",
    summary: "Provides testing requirements and reports relevant to buses acquired with FTA financial assistance.",
    ruralAction: "Verify the vehicle's testing status, route gradeability, reliability, range, and accessibility before procurement.",
    url: "https://www.transit.dot.gov/research-innovation/bus-testing"
  },
  {
    id: "fta-ada-part-37",
    title: "49 CFR Part 37 — Transportation Services for Individuals with Disabilities",
    issuer: "Federal Transit Administration",
    jurisdiction: "Federal",
    domain: "Accessibility",
    instrument: "Regulation",
    status: "In force",
    year: 1991,
    binding: true,
    rural: "Direct",
    summary: "Implements transportation-service requirements under the ADA, including requirements affecting fixed-route and demand-responsive service.",
    ruralAction: "Design booking, boarding, equivalent service, rider assistance, and paratransit coordination into the operating model.",
    url: "https://www.transit.dot.gov/regulations-and-guidance/civil-rights-ada/part-37-transportation-services-individuals-disabilities"
  },
  {
    id: "access-board-inclusive-av",
    title: "Inclusive Design of Autonomous Vehicles",
    issuer: "U.S. Access Board",
    jurisdiction: "Federal",
    domain: "Accessibility",
    instrument: "Design resource",
    status: "Current guidance",
    year: 2021,
    binding: false,
    rural: "Direct",
    summary: "Collects accessibility considerations for mobility, sensory, and cognitive access to automated vehicles.",
    ruralAction: "Co-design the rider journey with disabled rural residents, including non-app booking and support during connectivity loss.",
    url: "https://www.access-board.gov/advancing-access/initiatives/av/landing/"
  },
  {
    id: "fta-accessibility-scan",
    title: "Accessibility in Transit Bus Automation",
    issuer: "Federal Transit Administration",
    jurisdiction: "Federal",
    domain: "Accessibility",
    instrument: "Research report",
    status: "Planning resource",
    year: 2022,
    binding: false,
    rural: "Transferable",
    summary: "Reviews accessibility practices in automated transit demonstrations and research relevant to future service.",
    ruralAction: "Turn accessibility from a vehicle specification into an end-to-end service acceptance test.",
    url: "https://www.transit.dot.gov/research-innovation/accessibility-transit-bus-automation-scan-current-practices-and-ongoing"
  },
  {
    id: "fcc-cv2x",
    title: "C-V2X Rules for the 5.9 GHz Band",
    issuer: "Federal Communications Commission",
    jurisdiction: "Federal",
    domain: "Infrastructure",
    instrument: "Final rule",
    status: "In force",
    year: 2024,
    binding: true,
    rural: "Direct",
    summary: "Establishes technical and operational rules for C-V2X use in the upper 30 megahertz of the 5.9 GHz band.",
    ruralAction: "Confirm licensing, equipment, transition, and interference requirements before treating roadside V2X as deployable infrastructure.",
    url: "https://docs.fcc.gov/public/attachments/FCC-24-123A1.pdf"
  },
  {
    id: "nist-csf-2",
    title: "NIST Cybersecurity Framework 2.0",
    issuer: "National Institute of Standards and Technology",
    jurisdiction: "Federal",
    domain: "Data & cybersecurity",
    instrument: "Risk framework",
    status: "Current guidance",
    year: 2024,
    binding: false,
    rural: "Direct",
    summary: "Provides an outcome-based framework for governing and managing cybersecurity risk.",
    ruralAction: "Create a project cybersecurity profile spanning vehicle, fleet center, roadside equipment, vendors, and recovery during outages.",
    url: "https://www.nist.gov/cyberframework"
  },
  {
    id: "ftc-connected-cars",
    title: "Cars and Consumer Data",
    issuer: "Federal Trade Commission",
    jurisdiction: "Federal",
    domain: "Data & cybersecurity",
    instrument: "Enforcement guidance",
    status: "Current guidance",
    year: 2024,
    binding: false,
    rural: "Direct",
    summary: "Highlights risks from unlawful collection, use, and disclosure of sensitive connected-car data, including precise location.",
    ruralAction: "Minimize location, video, biometric, and rider data; document purpose, retention, access, sharing, and deletion.",
    url: "https://www.ftc.gov/policy/advocacy-research/tech-at-ftc/2024/05/cars-consumer-data-unlawful-collection-use"
  },
  {
    id: "ga-sb-219",
    title: "Georgia Senate Bill 219 — Fully Autonomous Motor Vehicles",
    issuer: "Georgia General Assembly",
    jurisdiction: "Georgia",
    domain: "Vehicle compliance",
    instrument: "State law",
    status: "In force",
    year: 2017,
    binding: true,
    rural: "Direct",
    summary: "Establishes Georgia provisions addressing fully autonomous vehicles, including operation, equipment, insurance, registration, and crash-related responsibilities.",
    ruralAction: "Map the exact vehicle, operator, insurance, registration, and incident duties to the planned Georgia deployment.",
    url: "https://www.legis.ga.gov/Legislation/20172018/170801.pdf"
  },
  {
    id: "ga-registration",
    title: "Georgia Vehicle Registration Requirements",
    issuer: "Georgia Department of Revenue",
    jurisdiction: "Georgia",
    domain: "Vehicle compliance",
    instrument: "Administrative requirement",
    status: "In force",
    year: 2026,
    binding: true,
    rural: "Direct",
    summary: "Describes Georgia vehicle registration and license-plate administration.",
    ruralAction: "Resolve titling, registration, VIN, fleet, and county processing questions before placing vehicles into service.",
    url: "https://dor.georgia.gov/motor-vehicles/vehicle-registration-license-plates"
  },
  {
    id: "ga-insurance",
    title: "Georgia Motor-Vehicle Insurance Coverage",
    issuer: "Georgia Department of Revenue",
    jurisdiction: "Georgia",
    domain: "Vehicle compliance",
    instrument: "Administrative requirement",
    status: "In force",
    year: 2026,
    binding: true,
    rural: "Direct",
    summary: "Describes continuous Georgia automobile-liability coverage and proof-of-insurance requirements associated with registration.",
    ruralAction: "Confirm coverage, fleet or self-insurance treatment, electronic reporting, and evidence carried with each vehicle.",
    url: "https://dor.georgia.gov/motor-vehicles/insurance/insurance-coverage"
  },
  {
    id: "gdot-cv-roadmap",
    title: "Georgia DOT Connected Vehicle Roadmap 2.0",
    issuer: "Georgia Department of Transportation",
    jurisdiction: "Georgia",
    domain: "Infrastructure",
    instrument: "Agency roadmap",
    status: "Planning resource",
    year: 2024,
    binding: false,
    rural: "Direct",
    summary: "Frames GDOT's connected-vehicle infrastructure direction and deployment context.",
    ruralAction: "Align any rural roadside-unit proposal with statewide architecture, operations ownership, communications, and maintenance plans.",
    url: "https://www.dot.ga.gov/systems/ProjectDocuments/Programs/ConnectedVehicles/GDOT_CVRoadmap_Roadmap_2.0_v1.3.pdf"
  }
];
